### ISSUE TITLE
Carved Blocks

### ISSUE THREAD

**Issue by daatguy** [daatguy/lovecraft-mod#19]
Blocks carved with messages in a language (held in associated TileEntity NBT data)

Right click on them with a dictionary of that language to see what they say

**Comment by UnrelatedString** [comment]
Some things to think about: should untranslated rubbings exist alongside on the spot translation or entirely supersede them, and in what way should the text actually be displayed?

**Comment by UnrelatedString** [comment]
Another thing we might want to consider is having some spells come from carvings.

**Comment by UnrelatedString** [comment]
...since it’s all NBT it shouldn’t be a problem to support both i18n text and raw text (and spells) alternately

**Comment by daatguy** [comment]
Spells from carvings is an interesting idea. I think we could implement those with the writing desk and crafting however--a translated rubbing might be a spell, etc.

This is something we should consider when figuring out how to add translation recipes for the rubbings--currently, there exist untranslated and translated rubbings, but no recipe for translating them in a writing desk.

**Comment by UnrelatedString** [comment]
We might want to have multiple categories of NBT that are handled differently and separately by the recipe--lore text, custom text, spells, crashing the game, etc.

I don't actually know how the recipe works really so I can't say how well that would work but it's an approach to think about I guess

**Comment by UnrelatedString** [comment]
This issue is probably ready to close once we resolve #42 -- we've done some good work on this
