### ISSUE TITLE
Altar GUI does not display mod items

### ISSUE THREAD

**Issue by daatguy** [daatguy/lovecraft-mod#33]
Yeah, title says it all. itemDriedFlower for instance displays as just "Air"

**Comment by daatguy** [comment]
Shift clicking them in doesn't work either--something weird in the container/slot classes idk

**Comment by UnrelatedString** [comment]
Seems like you can't even click them in without shift

**Comment by UnrelatedString** [comment]
Put some prints in `GuiAltar` and somehow *the recipe itself contains the air*.

**Comment by UnrelatedString** [comment]
...because the items hadn't been initialized.
