### ISSUE TITLE
Breaking carved blocks doesn't create item with nbt data

### ISSUE THREAD

**Issue by daatguy** [daatguy/lovecraft-mod#42]
Placing the item from a broken block makes a null carving ("carving.null")

**Comment by UnrelatedString** [comment]
Just about resolved, except you still get the `carving.null` message even though you can obtain the correct rubbing...!?!?

**Comment by UnrelatedString** [comment]
Well, if we're not sending chat messages from server side, we need to find some way to sync the tile entity with the remote world properly...

**Comment by UnrelatedString** [comment]
https://jabelarminecraft.blogspot.com/p/minecraft-forge-1721710.html might help, but I am still wondering what the problem is with sending chat messages from server side in multiplayer...
